---
bibliography: references.bib
---

# Introduction

Rhizaria are an extremely diverse super-group of single-celled organisms consisting of several phyla including Retaria (foraminifera and radiolaria) and Cercozoa. These organisms exist in a wide range of habitats and are widely represented in plankton communities throughout the global ocean. While the taxonomy of these organisms has recently undergone several reclassifications [@biard2022], their presence in ocean ecosystems has been long known to oceanographers. Some of the earliest records of their existence are from oceanographic expeditions in the 19th century [@haekel1887]. Rhizaria are unique members of the plankton and protist community because they can reach large sizes (up to several mm in diameter) and they construct intricate mineral skeletons out of either silica, strontium, or calcium carbonate [@kimoto2015; @suzuki2015; @nakamura2015; @biard2022]. Despite their noticeable morphology and global distribution, Rhizaria were largely understudied throughout the 20th century. The bulk of modern plankton research has focused on hard-bodied crustacea which are numerically dominant and easily sampled with nets and preservatives. Fragile organisms like Rhizaria, were difficult to adequately study as they can be destroyed through standard zooplankton sampling techniques and preserve poorly. A number of studies in the late 1900s did employ alternative techniques to quantify Rhizaria including diaphragm pumps [@michaels1988] or blue-water SCUBA collections [@caron1984; @caron1995; @bijma1990]. However, the bulk of Rhizaria research was constrained to sediment traps or paleontological studies of sediment [@takahashi1983; @boltovskoy1993]. Only recently has the advent of molecular techniques and in-situ imaging tools ignited a renewed focus on Rhizaria in pelagic ecosystems [@caron2016].

The wave of new data on Rhizaria has facilitated an improved understanding of the significance in ocean ecosystem functions. Firstly, taxonomists have been able to greatly refine the understanding of evolutionary relationships amongst these diverse protists [@aurahs2009; @decelle2012; @decelle2013; @biard2015; @cavalier-smith2018; rev by @biard2022]. DNA metabarcoding studies have revealed insights into the distributional patterns [@decelle2013; @biard2017; @marsbrisbin2020; @blanco-bercial2022 @llopismonferrer2022; @sogawa2022], ecological relationships [@decelle2012; @nakamura2023], and contribution to biogeochemical fluxes [@guidi2016; @gutierrez-rodriguez2019]. Transcriptomic and proteomic approaches also have been used to quantify rhizarian contribution to community metabolism [@cohen2023]. Yet, despite the excellent taxonomic resolution provided by molecular approaches, they do not provide a truly quantitative metric for estimating Rhizarian abundance or biomass. In-situ imaging tools however, offer the ability to observe organisms in the natural state and quantify their abundance [@ohman2019a; @barth-inrev]. While there were early applicaitons of imaging tools to document Rhizaria [@dennett2002], @biard2016's report from a global imaging dataset highlighted the importance of Rhizaria to the total standing stock of marine carbon. Due to their large sizes, ability to concentrate smaller particles and the unique structure of their mineral skeletons, Rhizaria have the potential to massively influence ocean biogeochemical cycling. A number of studies have made large advances in estimating the contribution of Rhizaria to ocean cycling of carbon [@lampitt2009; @stukel2018; @ikenoue2019; @gutierrez-rodriguez2019], silica [@biard2018; @llopismonferrer2021], and strontium [@decelle2013]. Still, Rhizarian ecological roles are not well understood [@biard2022]. This is a major challenge as it is critical to understand the ecological role of plankton to fully incorporate them into biological oceanographic models.

The ecological role of Rhizaria in plankton communities is complicated due to the fact different taxa can exhibit every different trophic modes. As zooplankton, rhizaria are predominately heterotrophic [@biard2022], yet their feeding modes can be quite varied. Phaeodarians (family Cercozoa) are largely thought to be flux-feeders, collecting and feeding on sinking particles [@nakamura2015; @stukel2019]. Alternatively, Retaria can be either exclusively heterotrophic or mixotrophic, utilizing photosynthetic algal symbionts [@anderson2014; @decelle2015]. Mixotrophic foraminifera host a variety of endosymbiont partners [@lee2006; @decelle2015], which are thought to support early and adult life stages and contribute to total primary productivity [@kimoto2015]. Still, foraminifera are omnivorous, possibly even predominately carnivorous with several studies suggesting that they can be effective predators [@anderson1976; @gaskell2019], mainly consuming live copepods [@caron1984]. Radiolaria have several lineages all which have some taxa who are well known to host symbionts [@biard2022b]. Amongst radiolarians, arguably the most widespread are Collodaria who can be either large solitary cells or form massive colonies, up to several meters in length [@swanberg1981]. All known Collodaria species host dinoflagellate symbionts [@biard2022b] and can contribute substantially to primary productivity, particularly in oligotrophic ocean regions [@caron1995; @dennett2002]. This Collodaria-symbiont association has been suggested as a reason for their high abundances throughout the photic zone of oligotrophic environments globally [@biard2016; @biard2017]. A few Acantharean (Radiolarian order) clades host algal symbionts [@decelle2012; @biard2022b], notably with two clades forming an exclusive relationship with Phaeocystis. However, globally Acantharea are less abundant than Collodaria [@biard2022] and contribute less to total primary productivity [@michaels1995]. This may be due to the fact several clades of Acantharea are cyst-forming and strictly heterotrophs [@decelle2013; @biard2022b]. Furthermore, @marsbrisbin2020 documented apparent predation behavior in Acantharea near the surface, suggesting that there may be a large reliance on carnivory.

Given the high abundances, yet diverse trophic strategies found among Rhizarian taxa, it is reasonable to expect some form of niche partitioning. A number of studies do suggest evidence for vertical zonation between Rhizaria groups according to various trophic strategies. Taxa-specific studies of radiolarians suggest they may be restricted to the euphotic zone [@michaels1988; @boltovskoy2017]. Although some studies report Acantharea in deeper waters [@decelle2013; @gutiérrez-rodríguez2022]. Phaeodarians alternatively, are generally found in the mesopelagic where photosynthesis cannot occur but they can feed on sinking particles [@stukel2018]. In an imaging-based study of the whole Rhizaria community, @biard2020 noted clear patterns in vertical zonation which largely corresponded to different trophic roles. In the oligotrophic ocean, @blanco-bercial2022 also noted that the protist community, including Rhizaria, partition along an autotroph and mixotroph to heterotroph gradient with increasing depth in the water column. Yet, few studies have made direct attempts to relate rhizaria abundances to environmental factors [@biard2020]. In part, this is due to the fact few studies have been able to sample Rhizaria in the same location over a consistent timeframe [@michaels1988; @boltovskoy1993; @michaels1995; @hull2011; @gutiérrez-rodríguez2022]. Furthermore, no studies have utilized imaging, arguably the best method for quantifying rhizaria, consistently throughout the full mesopelagic. Given this lack of information, there are many unknowns with respect to Rhizarian ecology, seasonality and phenology across different groups.

In this study, we present a comprehensive assessment of large Rhizaria measured for multiple months (greater than 1 year) using an in-situ imaging approach. With this dataset, we address two critical aims. 1) Quantification of large Rhizaria throughout the epipelagic (0-200m) and mesopelagic (200-1000m) over the course of an annual cycle. These data were collected in the Sargasso Sea, and represents the first study of its kind in an oligotrophic system. 2) We aim to test the hypothesis that Rhizaria exhibit niche partitioning according to trophic roles. This hypothesis makes several predictions, including vertical zonation, as seen in prior studies, but also that environmental variables related to trophic strategy will explain abundance patterns. Specifically, autotrophic/mixotrophic taxa will correspond to variables related to autotrophy (chl-a concentration, primary productivity, high $O_2$ ) and other rhizaria will correspond to factors which promote heterotrophy (particle concentration, flux, and low $O_2$).
