---
bibliography: references.bib
---

# Results

### Environmental Variability

The BATS sampling region is southeast of Bermuda, situated in the North Sargasso Sea and the North Atlantic oligotrophic ocean gyre. Due to the sampling location, while the environmental conditions are generally low in variation and oligotrophic, there is some seasonality and considerable influence from mesoscale eddies [@mcgillicuddy1998; @lomas2013]. Variability in the water column structure was visible during the study period (Figure 2). This is best evidenced through the temperature profiles; In the late summer and early fall there was a stratified water column with high temperatures in the surface (\<75m) (Figure 2A) and slightly elevated salinity (Figure 2B). This warm, stratified period appeared more intense during the few months sampled in 2019. In 2021, we observed the stratified layer slowly dissipated into the winter months. There was a consistent oxygen minimum zone (OMZ) located at about 750m deep (Figure 2C). Although, February 2021 saw a notable downwelling event, likely due to a passing cyclonic eddy. During this time, warmer, oxic water was plunged deeper into the mesopelagic. This process was reversed in the spring months (March, April) when mixing occurred throughout the epipelagic and the surface was cooler and well mixed. Primary production was highest during the spring mixing period, evidenced both by in-situ fluorescence (Figure 2D) and productivity incubation experiments (Figure 3A). Originating near the surface, the productivity peak moved deeper throughout the spring and declined into the summer (Figure 2D). However, there was a notable, yet smaller productivity bump in the late summer and early fall (Figure 3A) which occurred deeper in the epipelagic (Figure 2D). The particle concentration (184$\mu m$ - 450$\mu m$) was closely coupled to chlorophyll-a patterns.

Overall, particle concentration was high near the surface during the 2021 spring bloom, then moved deeper throughout the water column attenuating throughout the lower epipelagic (Figure 2E). Similarly, bacteria abundance was closely linked to overall productivity, althrough there was a more consistent moderate-abundance layer near the top of the mesopelagic (\~250m) (Figure 2F). Concurrent with the secondary fall production peak, there was also higher particle concentration and bacterial abundance in the later summer and early fall. Interestingly, while primary productivity estimates from July-August were not that different between 2019 and 2021 (Figure 4A), chlorophyll-a florescence, particle concentration, and bacterial abundance were much higher in 2019's summer/fall (Figure 2D-F). Inorganic nutrients ($Si$ and $NO_3$) were generally well stratified, with low concentrations in the epipelagic and increasing throughout the mesopelagic. However, both nutrients did vary vertically in accordance with the 2021 February downwelling and spring mixing period (Figure 2G-H). Additionally, in the late fall of 2021, $Si$ concentrations were slightly elevated in the mid-mesopelagic (Figure 2G).

Overall mass flux to the mesopelagic was highest during the 2021 February downwelling (Figure 3B). Generally, export was similarly high during March, declining in April then increasing slightly throughout the summer and early fall. While magnitude was slightly different, this pattern was consistent with total mass, carbon and nitrogen fluxes (Figure 3B-D). Higher mass, carbon and nitrogen flux also occurred in the 2019 late summer - early fall period.


### Rhizaria abundance and distribution

Across all imaged mesozooplankton (\>900$\mu m$), Rhizaria comprised a considerable fraction of the total community. Considering the total abundances of the observational period, Rhizaria comprised on average, 42.6% of all mesozooplankton abundance (Supplemental Figure 3). Copepods were the second most abundant, comprising 35.5% and all other living mesozooplankton were 22%. The large contribution of Rhizaria to the mesozooplankton community is most prominent in the epipelagic, where they accounted for 47% of all mesozooplankton. In the mesopelagic rhizaria were a smaller fraction, at 38% in the upper layers (200-500m) and 37% in the deeper mesopelagic (500-1000m).

Total average Rhizaria abundance had a bimodal distribution with respect to depth. Total abundance was highest just below the surface (0-100m), with secondary, wider peak occurring in the mid mesopelagic (Figure 4A). Variation in depth binned abundance was large, likely due to seasonal variability but also increased from the detection-risk described in the methods. The vertical distribution pattern and abundance varied considerably across taxonomic groups. Radiolarians were some of the most abundant taxa observed, particularly in the epipelagic (Figure 4, Figure 5B). This pattern was led by Collodaria, whose colonies were abundant in the upper epipelagic and declined into the top of the mesopelagic (Figure 4C). Acantharea displayed a bimodal distribution accounting for a large portion of the total Rhizaria pattern (Figure 4B, Figure 5). Foraminifera had a similar bimodal distribution, yet their overall average densities were much lower and spread wider throughout the mesopelagic (Figure 4E). Phaeodarian families exhibited a wide range of vertical distribution patterns. The most abundant, Aulacanthidae, also had a bimodal pattern but the density was highest in the lower mesopelagic (Figure 4D). Aulosphaeridae had low average density and was nearly homogeneously distributed throughout the water column, although slightly lower in the epipelagic (Figure 4F). Castanellidae were the only Phaeodarian who appeared to be effectively restricted to the photic zone (Figure 4G). Alternatively, Coelodendridae primarily occurred in the lower mesopelagic (Figure 4H). A few individuals from the families Tuscaroridae and Medusettidae were also observed in the mesopelagic, yet they were much rarer (data not shown).

Between the monthly cruises, Rhizaria integrated abundance varied in the epipelagic. Highest average abundance occurred in June 2021 and was lowest during the winter months (Figure 5A). The 2019 later summer - fall period also had much higher integrated abundance than similar months in 2021. While the majority of integrated abundance in the epipelagic was consistently attributable to Collodaria, Acanthrean abundance occurred sporadically and could account for a large portion of the total in some months (Figure 5B). The mesopelagic integrated abundance was much more consistent across monthly cruises, although average abundance was notably higher in 2019 (Figure 5C-F). The community composition in the mesopelagic was more diverse, mostly comprised of Phaeodarians. However, Acantharea and unidentified Rhizaria also were common members of the community (Figure 5D, 5F).


### Body size throughout the water column.

Very few taxa had consistent distributions throughout the water column. Only Acanthrea, Foraminifera, Aulacanthidae, and Aulosphaeridae were consistently abundant in the epipelagic and mesopelagic. To investigate if the populations or morphologies shifted throughout the water column, we compared the sizes (Equivalent Spherical Diameters, ESD) between mesopelagic and epipelagic groups for each taxa. All groups were significantly different on average (Wilcox Rank Sum p-value <0.001). Acantharea were smaller, on average in the mesopelagic while all other taxa tended to be larger (Figure 6).

### Environmental Drivers of Rhizarian Abundance

For total Rhizarian integrated abundance the GAMs produced moderate fits ($R^2_{adj}$ = 0.406-0.603) (Table 1). In the epipelagic, there were several significant predictor variables including inorganic nutrients ($NO_3$ and $Si$), water quality parameters (Salinity, DO), primary production, and particle concentration (Table 1). However, the upper and lower mesopelagic were exclusively explained by particle-related variables (concentration and mass flux) (Table 1).

GAMs for individual taxa were much less consistent in their fits (Table 2). This is likely in part due to the high number of non-observations for certain taxa. Note that due to low abundances, GAMs were not constructed for Tuscaroridae or Medusettidae. Furthermore no significant terms were found for a model with Aulosphaeridae in the epipelagic nor Foraminifera in the mesopelagic.

Epipelagic Acantharea were explained by several predictor variables and had a good fit ($R^2_{adj}$ = 0.53, Table 2). Most notable smooths were mass flux and particle concentration, which had a weak positive association (Figure 7A), with July 2021 as a clear outlier where Acantharean abundances were high in the epipelagic despite lower fluxes and particle concentrations (Figure 5). Foraminifera had a good fitting GAM in the epipelagic ($R^2_{adj}$ = 0.445). There were several significant explanatory variables, although the clearest pattern was observed of high temperatures associated with more Foraminifera abundance (Table 2, Figure 7B). Epipelagic Aulacanthidae similarly had several predictor variables which were significant, including both water quality parameters and particle/flux predictors (Table 2). Interestingly, Aulacanthidae had primary production as a significant predictor, yet there was not a clear association (Figure 7C). There was a fit for Collodaria in the epipelagic ($R^2_{adj}$ = 0.16), although there was a logit-like relationship where higher abundances tended to occur during higher DO conditions in the surface waters (Figure 7D). Castanellidae also had similarly poor fits in the epipelagic ($R^2_{adj}$ = 0.124) (Table 2, Figure 7E).

In the upper mesopelagic (200-500m), abundances were generally low (Figure 4) so GAMs were only constructed for Acantharea, Aulacanthidae, Aulosphaeridae, and Coelodendridae (Table 2). All these models had generally poor fits ($R^2_{adj}$ \< 0.25). Yet, for all upper mesopelagic models, particle concentration was a significant explanatory variable (Table 2, Figure 8). Carbon flux was significant for Acantharea and nitrogen flux was significant for both Acantharea and Coelodendridae (Table 2, Figure 8A,D). The lower mesopelagic also had generally poor GAM fits for taxa specific models ($R^2_{adj}$ \<0.3), with the exception of Acantharea ($R^2_{adj}$ = 0.509). Acantharea in the lower mesopelagic was most clearly positively associated with particle concentration and nitrogen flux, as well as temperature to a slight degree (Figure 9A). For all Phaeodarians with a significant model, particle concentration was a main predictor variable (Table 2, Figure 9B-D). Aulacanthidae had the best fitting model of the Phaeodarians ($R^2_{adj}$ = 0.298), which also included mass flux as a statistically significant smooth (Figure 9B).




