---
bibliography: references.bib
---

# Discussion

### Overall Rhizaria abundance and patterns

In the epipelagic Rhizaria exhibited a notable seasonal pattern. Rhizaria abundances were higher in the summer months and lower during the winter. During a prior time period, @blanco-bercial2022 noted that there is considerable seasonality in the community composition of all protists. Despite the seasonality of total Rhizaria abundance, community composition was relatively consistent, with Collodaria representing the bulk of the community. It should be noted that the overall taxonomic resolution of the UVP5 is fairly low, so there may be a switching of species within the broad groups identified in this study which were not captured. Throughout the mesopelagic, month-to-month variation in 2021 was relatively low. Again, this is consistent with observations from metabarcoding of the whole protist community in the same study region [@blanco-bercial2022]. This finding is not surprising as the overall seasonal variation in environmental conditions in this region were low.

Overall Rhizaria were the most commonly identified group of mesoplankton throughout the study period. We do note that the UVP5 commonly captures *Trichodesmium* colonies, yet these were excluded in this comparison as they are strictly autotrophs. It should be noted that previous work has suggested that avoidance behavior with the UVP is possible, at times likely, for visual and highly mobile zooplankton [@barth2022]. Thus, the percent contribution reported here (42.7%) of Rhizaria to the total mesozooplankton community may be inflated due to under sampling of organisms such as Euphausiids and Chaetognaths which have quick escape responses. Regardless, it is worth noting that in the same region, with data collected in 2012 and 2013 using similar calculation methods, @biard2016 estimated Rhizaria only contribute 15% of the total mesozooplankton community in the upper 500m. Likely, Rhizaria display considerable interannual variability. In the present study, we noticed considerably higher Rhizaria abundance throughout the water column in 2019 compared to 2021. While this may have been driven by increased mass flux, more information is needed to truly understand the magnitude by which Rhizaria can vary interannually.

### Relationship to environmental parameters

In general, the fit of most GAMs were moderate to poor. One possible reason for the poor fits may have been that for some taxa, conditions were not variable enough to capture a range of conditions at which they may exist. For instance, Collodaria were the most abundant taxa observed, yet the fit of their GAM was particularly poor. In studies which covered a wider range of parameters, Collodaria has been shown to strongly vary with changes in parameters such as temperature, chlorophyll-a, mixing, and water clarity [@biard2017; @biard2020]. Alternatively, Acantharea had relatively good fitting GAMs. These taxa also had some of the largest variation from month to month on cruises. Thus, it may be that in the oligotrophic, the relatively stable conditions can support certain taxa while others are more sporadic. It should also be noted that due to the challenge of adequately sampling enough volume to overcome low-detection issues, GAMs were run on integrated data. However, variation with environmental parameters throughout the water column are likely, just not captured in the modelling aspect of this study. One consistent parameter which had significant positive associations was particle concentration. This observation is not surprising as most rhizaria likely to some extent engage in flux feeding.

### Vertical Structure and Trophic Roles

In this study we present a clear pattern of vertical zonation between different Rhizaria groups. Largely, the taxonomic composition and vertical positioning were similar to Rhizaria zonation in the California Current Ecosystem [@biard2020]. It should be noted however, that the secondary abundance peak reported in the present study is lower. This is likely due to the more oligotrophic nature of the study region, were the euphotic zone penetrates deeper into the water column. Most prevalent in the epipelagic were Collodaria. These mixotrophic Radiolarians have long been reported to contribute to primary productivity in the euphotic zone [@michaels1995; @dennett2002]. Collodaria are thought to be particularly successful globally in oligotrophic regions due to their photosymbiotic relationships [@biard2016; @biard2017]. We observed the highest abundance of Collodaria during June 2021, supporting the notion they can thrive during the typically low-nutrient conditions of summer stratification. However, Collodaria also increased during the spring mixing period, suggesting that they can thrive during conditions which may typically be thought to favor autotrophs. Furthermore, while Collodaria were primarily absent from below 250m, there were a few instances of deeper colonies being observed. Global investigations of polycystine flux, suggest that deep-Collodaria in Oligotrophic regions may be a consequence of isothermal submersion [@boltovskoy2017]. Alternatively, surface waters at BATS often mix into the mode water during the seasonal mixing, so Collodaria in the deeper waters may be a result of diapyncal mixing. Another effectively exclusively epipelagic Rhizaria was the Phaeodaria family of Castanellidae. All Phaeodaria are thought to be fully heterotrophic [@nakamura2015], nonetheless a number of studies, including this one, report Castanellidae to be typically found in the lower epipelagic [@zasko2005; @biard2018; @biard2020]. It should be considered that perhaps Castanellidae specializes in feeding on sinking particles directly at the base of the epipelagic. Given it's smaller size [@nakamura2015], Castanellidae does not need a large diameter to efficiently flux feed at the typically particle rich region of the lower epipelagic. Both Castanelldiae and Collodaria had poor fitting GAMs. This is somewhat of a surprise for Collodaria who had large abundance. However, given the consistency of their abundance, it may be that this study did not capture a wide enough range of conditions for describing Collodaria's preferred niche.

The mesopelagic generally was home to known heterotrophic organisms, particularly for those which were constrained to exclusively occupy deeper waters. This is consistent with @blanco-bercial2022's observation of an auto-/mixotroph to heterotroph gradient in the protist community. The upper mesopelagic interestingly had relatively low total abundance. This low-abundance region likely reflects the dynamics of productivity and export throughout the water column. While productivity and thus sinking particles for flux feeders are high in the euphotic zone, much of this is attenuated throughout the epipelagic. So, while the base of the epipelagic may provide a rich feeding environment for Castanellidae, smaller protists, or heterotrophic bacteria (Figure 2F), the region from 200-500m might be otherwise food poor. Perhaps it is more advantageous for Rhizaria to situate deeper, in darker regions of the twilight zone. Also it should be noted that Phaeodaria utilize silica to build their opaline tests, and silica concentrations started to increase around 500m (Figure 2G). Although $Si$ was not a significant smooth for any taxa-specific model, this lack of association might be due to the overall lack of variation of $Si$ between integrated abundance of each cast. Aulosphaeridae was only found to have significant relationships, although weak fits, to particle concentration in the mesopelagic. In our study, while consistently observed, overall abundances of Aulosphaeridae were very low. In the Pacific Ocean, on California's Coast, much higher abundances of Aulosphaeridae have been reported [@zasko2005; @biard2020] and they have massive potential to impact silica export [@biard2018]. Coelodendridae were also seemingly restricted to the deeper section of the mesopelagic. This is interesting given that in the California Current, [@biard2020] found a bimodal distribution in Coelodendridae. There are several morphotypes corresponding to different taxa of Coelodendridae [@nakamura2015; @biard2020]. So it may be that only a few types of Coelodendridae were observed in this study, while the epipelagic variety was not. Alternatively, the lower epipelagic of the California Current may provide adequate habitat for Coelodendridae, which is not available in the oligotrophic Sargasso Sea.

A number of taxa were found to have a bimodal distribution, with considerable populations in both the epipelagic and mesopelagic. Aulacanthidae had a bimodal distribution, although abundances were highest in the lower mesopelagic. Foraminifera also had a bimodal distribution. Some lineages of Foraminifera are known to host photosymbionts [@kimoto2015; @biard2022], however they are also efficient predators commonly seen throughout the mesopelagic [@caron1984; @gaskell2019]. Thus it is not surprising to find their presence in both locations of the water column. Foraminifera are also known to vary their vertical distribution across their life cycle in phase with lunar cycles [@bijma1990; @kimoto2015; @gaskell2019; @biard2022]. However, the sampling scheme of the BATS program does not capture this frequency and was not investigated in the present study.

Acantharea also had a bimodal distribution, with much larger abundances than Aulacanthidae or Foraminifera. Most prior studies of Acantharea vertical distribution found them concentrated in near surface layers of the water column [@michaels1988 @zasko2005; @biard2020]. This would support the paradigm that large Acantharea abundances may be supported by their mixotrophic abilities [@michaels1995; @suzuki2015]. While the UVP5 images cannot distinguish between mixotrophic and heterotrophic Acantharea, the GAMs constructed for Acantharea abundance found positive associations with particle concentration and mass flux, suggesting a higher reliance on heterotrophy. Recently @marsbrisbin2020 described apparent predator behavior amongst near-surface Acantharea. Thus it is likely that epipelagic Acantharea may commonly be heterotrophic. Yet, it should be noted in the Sargasso Sea, both heterotrophic and symbiotic lineages of Acantharea have been reported [@blanco-bercial2022]. Additionally, @michaels1988 noted that the majority of Acantharea (by abundance) were smaller than 160$\mu m$. While that estimate may be inflated due to inability to capture larger cells, small Acantharea were not captured in the present study. Thus, trophic strategy may shift based on sizes of Acantharea.

@decelle2013 proposed a hypothetical life cycle for cyst-bearing (strictly heterotrophic) Acantharea. This hypothesized life cycle suggests that epipelagic Acantharea are adult populations, which form cysts that sink into the mesopelagic, then reproduce and rise. Furthermore, given that horizontal transfer of symbionts between generations of Acantharea is unlikely due to their spawning behavior, the newly spawned mesopelagic Acantharea are not necessarily required to rapidly return to the photic zone [@decelle2012; @decelle2013]. This hypothesis predicts that Acanthareas in the mesopelagic would be smaller [@decelle2013]. @marsbrisbin2020 provided some support for this hypothesis, with a significant decrease in Acantharea sizes with depth. Although the authors also observed low abundances in the mesopelagic and noted that the smaller sizes may be due to lower food availability [@marsbrisbin2020]. Since food is more scarce in the mesopelagi, nutritional quality lower, yet flux feeders would likely grow larger to increase their feeding range [@biard2020]. In the data collecting in this study, Acanthareas in the mesopelagic were significantly smaller than the epipelagic, despite the other bimodal taxa (Foraminifera and Aulacanthidae) being significantly larger with depth. This provides added support for the hypothesis that cyst-forming Acantharea may utilize different sections of the water column throughout their life cycle. However to further investigate this, more work is needed with higher temporal and taxonomic resolution.

### Conclusions and Considerations

This study provides a detailed look at Rhizaria abundance over time throughout the water column in a major oligotrophic gyre. We show that their abundances are generally related to particle concentration and flux, although lack of environmental variability may have reduced the fit of our GAMs. Considering the potential role of Rhizaria in the biological carbon pump, they may have a somewhat mixed role. In the shallower regions, where smaller Rhizaria are abundant, they may be an attenuating force on sinking particles [@stukel2019]. It should be noted that in our study, we focused on the "small" particle concentration field (\<450$\mu m$), and these particles are generally slower sinking than large particles. However, once consumed and repackaged by larger Rhizaria, they can sink quicker and contribute more to overall flux [@michaels1988]. Thus, Rhizaria may act as an aggregation mechanism. However, this is largely speculation, to truly test this, more work is needed measuring Rhizaria flux.

The vertical partitioning documented in this study do support the hypothesis that mixotrophic rhizaria will occupy shallower waters while deeper waters are dominated by heterotrophy. However the degree to which mixotrophic Rhizaria in the euphotic zone rely on heterotrophy versus symbiosis is uncertain. Collodaria were recorded as consistent and dominant members of the near surface region. These organisms have the potential to contribute considerably to the otherwise low productivity of oligotrophic regions. However, their role in food webs is not well understood. While this study represents a step-forward in our understanding of Rhizaria ecology, continued research on Rhizaria is much needed to better understand their ecology. Particularly extended descriptive work to capture interannual patterns. Also work defining biotic interactions, feeding rates, productivity, and life history are all rich fields of interest in Rhizaria.
