---
title: Rhizaria in the oligotrophic ocean exhibit clear temporal and vertical variability.
bibliography: references.bib
csl: ./deep-sea-research-part-i.csl
execute:
  echo: false
  warning: false
  message: false
author:
  - name: Alex Barth*
    affiliations:
    - name: University of South Carolina
      department: Biological Sciences
      address: 700 Sumter St 401, Columbia, SC 29208
    - name: University of Texas at Austin
      department: Marine Science Institute
      address: 750 Channel Drive, Port Aransas, Texas, USA
      email: alexander.barth1@austin.utexas.edu
  - name: Leocadio Blanco-Berical
    affiliations:
    - name: Arizone State University
      department: School of Ocean Futures
      address: Bermuda Institute of Ocean Sciences 17 Biological Station, St Georges, GE 01
  - name: Rod Johnson
    affiliations: 
    - name: Arizone State University
      department: School of Ocean Futures
      address: Bermuda Institute of Ocean Sciences 17 Biological Station, St Georges, GE 01
  - name: Joshua Stone
    affiliations:
    - name: University of South Carolina
      department: Biological Sciences
      address: 700 Sumter St 401, Columbia, SC 29208
format:
  pdf:
    template-partials:
      - "before-body.tex"
      - "_titlepage.tex"
    include-in-header:
      - "in-header.tex"
    number-sections: false
    linestretch: 2
    tbl-cap-location: top
    filters: [wordcount.lua]
    keep-tex: true
    tbl-colwidths: [43, 33.75, 7.75, 7.75, 7.75]
    geometry:
      - left=1in
      - textwidth=6.5in
      - right=1in
      
abstract: |
  Recently studies have shown that Rhizaria, a super-group of marine protists, have a large role in pelagic ecosystems. They are unique in that they construct mineral tests out of silica, calcium carbonate, or strontium sulfate. As a consequence, Rhizaria can have large impacts on the ocean’s cycling of carbon and other elements. However, less is known about Rhizaria ecology or their role in the pelagic food-web. Some taxa, like certain Radiolarians, are mixotrophic, hosting algal symbionts. While other taxa are flux-feeders or even predatory carnivores. Some prior research has suggested that Rhizaria will partition vertically in the water column, likely due to different trophic strategies. However, very few studies have investigated their populations over extended periods of time. In this study, we present data investigating Rhizaria abundance and vertical distribution from over a year of monthly cruises in the Sargasso Sea. This study represents the first quantification of Rhizaria throughout the mesopelagic zone in an oligotrophic system for an extended period of time. We use this data to investigate the hypothesis that Rhizaria taxonomic groups will partition due to trophic mode. We also investigate how their abundance varies in accordance with environmental parameters. Rhizaria abundance was quantified using an Underwater Vision Profiler (UVP5), an in-situ imaging device. Ultimately, we show that different Rhizaria taxa will have unique vertical distribution patterns. Models relating their abundance to environmental parameters have mixed results, yet particle concentration is a common predictive variable, supporting the importance of heterotrophy amongst many taxa.
---

```{r}
#| child: ./01_intro.qmd
```

```{r}
#| child: ./02_methods.qmd
```

```{r}
#| child: ./03_results.qmd
```

```{r}
#| child: ./04_discussion.qmd
```

# References:

::: {#refs}
:::

